name: artifact

on: [push]

env:
  ARTIFACT_NAME: vicsart

jobs:
  main:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Upload artifact for linux
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
